version: "3.7"
services:
    webserver:
        image: traefik:v2.8
        restart: unless-stopped
        command:
            - --experimental.http3=true
            - --log.level=DEBUG
            - --api.insecure=true
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - ${WEB_PORT:-80}:80
        links:
            - php

    php:
        build:
            dockerfile: .docker/php/Dockerfile
            context: ./
        command:
            - vendor/bin/wait-for-it.sh
            - db:3306
            - --strict
            - --
            - ./rr
            - serve
            - -o
            - http.pool.num_workers=${RR_WORKERS}
        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
        restart: unless-stopped
        volumes:
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini:ro
            - ./.docker/data/composer:/home/appuser/.composer
            - ./project:/var/www
        environment:
            TZ: Europe/Moscow
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_LOGIN: ${DB_LOGIN}
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-}
            YII_DEBUG: 'true'
            YII_ENV: ${YII_ENV:-dev}
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
            XDEBUG_CONFIG: "client_host=host.docker.internal"
            XDEBUG_TRIGGER: "yes"
        env_file:
            - .env
        depends_on:
            - db
        extra_hosts:
            - host.docker.internal:${HOST_IP:-host.docker.internal}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.app.rule=Host(\"${DOMAIN}\")"
            - "traefik.http.routers.app.entrypoints=web"

    db:
        image: mysql:8.0
        restart: unless-stopped
        volumes:
            - .docker/data/db:/var/lib/mysql
        ports:
            - ${DB_PORT:-3306}:3306
        environment:
            TZ: Europe/Moscow
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_LOGIN}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
