version: "3.7"
services:
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        volumes:
            - ./src:/var/www
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - ${WEB_PORT:-80}:80
        links:
            - php
    php:
        image: ${DOCKER_REGISTRY}/${APP_NAME}:${BUILD_TAG:-latest}
        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
        volumes:
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini:ro
            - ./.docker/data/composer:/root/.composer
            - ./src:/var/www
        environment:
            TZ: Europe/Moscow
            XDEBUG_CONFIG: "remote_enable=On remote_host=${HOST_IP}"
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_LOGIN: ${DB_LOGIN}
            YII_ENV: ${YII_ENV:-prod}
        env_file:
            - .env
        links:
            - db

    db:
        image: postgres:11-alpine
        restart: on-failure
        volumes:
            - .docker/data/db:/var/lib/postgresql/data
        environment:
            TZ: Europe/Moscow
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_LOGIN}
