version: 3

silent: false

vars:
  dockerfileOverride:
    sh: \[ -f ./docker-compose.override.yml \] && echo '-f docker-compose.override.yml' || echo ''

tasks:
  up:
    env:
      USER_ID:
        sh: id -u
      GROUP_ID:
        sh: id -g
    cmds:
      - docker-compose -f ./docker-compose.yml {{.dockerfileOverride}} up -d --remove-orphans
    status:
      - docker-compose exec -T php echo ''

  down:
    cmds:
      - docker-compose down

  run:
    env:
      USER_ID:
        sh: id -u
      GROUP_ID:
        sh: id -g
    cmds:
      - docker-compose -f ./docker-compose.yml {{.dockerfileOverride}} run --rm {{if .workdir}}-w {{.workdir}}{{end}} {{if .envvars}}{{.envvars}}{{end}} {{.service}} {{if .CLI_ARGS}}{{.CLI_ARGS}}{{end}}

  php:restart:
    cmds:
      - docker-compose restart php

  php:psalm:
    deps: [ up ]
    ignore_error: true
    cmds:
      - docker-compose exec php php vendor/bin/psalm

  php:unit:
    deps: [ up ]
    cmds:
      - docker-compose exec php php vendor/bin/phpunit

  php:infection:
    deps: [ up ]
    cmds:
      - docker-compose exec -e XDEBUG_MODE=coverage php php vendor/bin/roave-infection-static-analysis-plugin --only-covered

  php:test:
    cmds:
      - task: php:psalm
        ignore_error: true
      - task: php:unit
      - task: php:infection

  php:exec:
    deps: [up]
    cmds:
      - docker-compose exec php {{.CLI_ARGS}}

  php:run:
    desc: Run the given command in a php container (run --rm).
    summary: |
      Run the given command in an php container (run --rm). You can use these parameters:
        - xdebug - the container will be run with the given xdebug mode (e.g. "off" or "debug")
      Example: task xdebug=coverage php:run -- vendor/bin/phpunit
    cmds:
      - task: run
        vars:
          service: php
          envvars: "{{if .envvars}}{{.envvars}}{{end}} {{if .xdebug}}-e XDEBUG_MODE={{.xdebug}}{{end}}"
          CLI_ARGS: "{{.CLI_ARGS}}"

  yii:
    cmds:
      - task: php:run
        vars:
          CLI_ARGS: php ./yii {{if .CLI_ARGS}}{{.CLI_ARGS}}{{end}}

  yii:migrate:
    cmds:
      - task: yii
        vars:
          CLI_ARGS: migrate --interactive=0

  yii:migrate:fresh:
    cmds:
      - task: yii
        vars:
          CLI_ARGS: migrate:fresh --interactive=0

  composer:i:
    cmds:
      - task: php:run
        vars:
          CLI_ARGS: composer install

  composer:u:
    cmds:
      - task: php:run
        vars:
          CLI_ARGS: composer update {{if .CLI_ARGS}}{{.CLI_ARGS}}{{end}}

  composer:rq:
    cmds:
      - task: php:run
        vars:
          CLI_ARGS: composer require {{.CLI_ARGS}}

  composer:rm:
    cmds:
      - task: php:run
        vars:
          CLI_ARGS: composer remove {{.CLI_ARGS}}

  composer:yii-cfg:
    cmds:
      - task: php:run
        vars:
          CLI_ARGS: composer yii-config-rebuild
